server:
  port: 8082

name: 张三

# 对象配置
person:
  name: 张张
  age: 18
  addr: china

# 行内配置
student: {name: lisi, age: 17, addr: American}

# 配置数据、集合
list:
  - zhangsan
  - lisi
  - wang


list2: [zhangsan, lisi, wang]

students:
  - name: zhangsan
    age: 17
  - name: tom
    age: 16
students2: [ { name: zhangsan, age: 17 }, { name: lisi, age: 16 } ]



# map配置
map:
  key1: value1
  key2: value2