# 字符串默认不用加引号
# 单引号：会进行转义，\n会原样输出
# 双引号：不会转义，例如\n时换行符，默认就是换行符


# 对象的两种写法
#person01:
#  name: zhangsan
#  age: 18


#person02: {name: zhangsan, age: 18}



# 数组list、set
#pets01:
#  - cat
#  - dog
#  - bird

#pets02: [cat, dog, bird]




#person:
#  name: zhangsan
#  age: 18
#  boss: false
#  birth: 2019/1/1
#  map: {k1:v1, k2:v2}
#  lists:
#    - s1
#    - s2
#  dog:
#    name: 二哈
#    age: 2

# yml中以---分割不同的环境配置
# properties文件的优先级在yml文件之前
# 为了不影响现将相关配置注释掉
server:
  port: 8081

# 除了在配置文件中激活，还可以使用下面两种方式激活
# VM Options: -Dspring.profiles.active=dev
# Program arguments: --spring.profiles.active=prod
spring:
  profiles:
    active: dev
---

server:
  port: 8082
spring:
  profiles: prod




---

server:
  port: 8083
spring:
  profiles: dev







